### ISSUE TITLE
Improving documentation and README.md

### ISSUE THREAD

**Issue by magnuspalmblad** [524D/mzrecal#1]
As the manuscript nears completion, could we update the README Markdown to reflect the narrative in the manuscript, and using a similar figure as in the manuscript? It does not have to be the same dataset, but presented in the same style for clarity and consistency. The "aim" of the software is also described well in the manuscript. Perhaps we can borrow and condense that narrative here?

**Comment by 524D** [comment]
The README is now updated with your changes and some further cleanup.
